#version: '3'

services:
    # App service
    nginx:
        container_name: nginx
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - ${DEFAULT_PORT}:8001
            - ${ADMINER_PORT}:8082
        working_dir: /var/www/html
        volumes:
            - ${DEFAULT_DIR}:/var/www/html/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/adminer.conf:/etc/nginx/conf.d/adminer.conf
            - ./nginx/adminer.php:/var/www/html/adminer/index.php
        depends_on:
            - php
        networks:
            - laravel_network

    # MySQL service
    mysql:
        container_name: mysql
        image: mysql:latest
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${DOCKER_DB_PORT}:3306
        networks:
            - laravel_network

    php:
        container_name: php
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        working_dir: /var/www/html/app
        volumes:
            - ${DEFAULT_DIR}:/var/www/html/app
            - ./nginx/adminer.php:/var/www/html/adminer/index.php
        ports:
            - ${APP_PORT}:80
        depends_on:
            - mysql
        networks:
            - laravel_network

    # Next.js service
    nextjs:
        container_name: nextjs
        image: node:20.9.0-alpine
        restart: unless-stopped
        tty: true
        volumes:
            - ${ADMIN_FRONTEND_DIR}:/admin
            - ${CONSUMER_FRONTEND_DIR}:/frontend
        ports:
            - ${FRONTEND_PORT}:3000
        networks:
            - laravel_network
networks:
    laravel_network:
